version: '3'
services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data:/var/lib/postgresql/data/application
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@sages.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "database"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_DATABASE: "shop"
    ports:
      - "8100:8080"
