spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver
keycloak:
  realm: shop
  resource: shop-rest
  public-client: true
  auth-server-url: http://localhost:8100/auth
